services:
  postgres:
    image: postgres:17.1
    env_file:
      - "./database.env"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  user_service:
    image: userimage
    command: sh -c "uvicorn main:app --host 0.0.0.0"
    build:
      context: ./user_service
      dockerfile: Dockerfile
    ports:
      - 8001:8000
    volumes:
      - ./user_service:/app
    depends_on:
      - postgres
