CREATE TABLE IF NOT EXISTS users(
	id VARCHAR PRIMARY KEY NOT NULL,
	login VARCHAR(50) NOT NULL UNIQUE,
	password bytea NOT NULL,
	name VARCHAR(60) NOT NULL,
	email VARCHAR(254) 
);

CREATE TABLE IF NOT EXISTS databases(
	id VARCHAR PRIMARY KEY NOT NULL,
	db_name VARCHAR(40) UNIQUE,
	db_system VARCHAR(40),
	password bytea NOT NULL,
	user_id VARCHAR REFERENCES users(id) ON DELETE CASCADE
)
